// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4jmnes4e_swD1uQtDeO-bln8pDKqYso',
    appId: '1:166253036259:web:297cd53b989462b455bbd6',
    messagingSenderId: '166253036259',
    projectId: 'vitaspace-a88ea',
    authDomain: 'vitaspace-a88ea.firebaseapp.com',
    storageBucket: 'vitaspace-a88ea.firebasestorage.app',
    measurementId: 'G-0VJH25Z5F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcrfrDk7JJClDSk4RiP02MXgWBBc_GJjI',
    appId: '1:166253036259:android:a38eee320487f47955bbd6',
    messagingSenderId: '166253036259',
    projectId: 'vitaspace-a88ea',
    storageBucket: 'vitaspace-a88ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmvlVMedSsn2Zwk2vvkQr6ofXzKEz0XNE',
    appId: '1:166253036259:ios:0f033f409d15da5b55bbd6',
    messagingSenderId: '166253036259',
    projectId: 'vitaspace-a88ea',
    storageBucket: 'vitaspace-a88ea.firebasestorage.app',
    iosBundleId: 'com.example.vitaspaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmvlVMedSsn2Zwk2vvkQr6ofXzKEz0XNE',
    appId: '1:166253036259:ios:0f033f409d15da5b55bbd6',
    messagingSenderId: '166253036259',
    projectId: 'vitaspace-a88ea',
    storageBucket: 'vitaspace-a88ea.firebasestorage.app',
    iosBundleId: 'com.example.vitaspaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG4jmnes4e_swD1uQtDeO-bln8pDKqYso',
    appId: '1:166253036259:web:47b48858476e899b55bbd6',
    messagingSenderId: '166253036259',
    projectId: 'vitaspace-a88ea',
    authDomain: 'vitaspace-a88ea.firebaseapp.com',
    storageBucket: 'vitaspace-a88ea.firebasestorage.app',
    measurementId: 'G-FC4DN2GSDD',
  );
}
